### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Tank-Missile** [the-realest-stu/Dynamic-Trees-BOP#1]
Is it currently possible to build this addon in its current state? I wanted to jump on board and test it out after I saw the reddit post. Unfortunately, gathering the needed dependencies and attempting to build it produces errors.

**Comment by the-realest-stu** [comment]
You need to add dynamic trees 0.7.4 and the latest version of Biomes O' Plenty to the libs folder of your workspace before setting up the workspace with gradle.

**Comment by Tank-Missile** [comment]
Dynamic Trees 0.7.4 lacks the LeaveProperties.java file, resulting in build errors. I assume this is due to changes within the last couple of hours? I ended up using the master branch, and got these errors instead: https://hastebin.com/odufotafin.coffeescript

**Comment by ferreusveritas** [comment]
He meant the dev version of DT that's currently at 0.7.5a.  You'll need to build that first.

**Comment by Tank-Missile** [comment]
I got it working. It's simply incredible. I'll report back my findings to help with development.

**Comment by ferreusveritas** [comment]
What would be particularly useful is if you could test it in a stand alone server with a separate client.  Server bugs always seem to be caught too late.
