### ISSUE TITLE
1.1.0a - crash before main menu, probably because of disabled BOP biome(s)

### ISSUE THREAD

**Issue by Febilian** [the-realest-stu/Dynamic-Trees-BOP#11]
https://gist.github.com/Febilian/99bb7b4b63bb5f9903cd684f77a2f348

Took me a bit to connect the dots between "this update added support for hellbark trees" and "I specifically have BOP's nether biomes disabled by setting their biome IDs to -1 in the BOP config files" as a potential cause for this.

It's possible that setting any BOP biome ID to -1 will cause this crash if a tree that only generates in that specific kind of biome tries to figure out where to generate. May be worth looking into!

**Comment by ferreusveritas** [comment]
Thank you for your insight.  It's details like this that allow us to fix problems like this rapidly.

**Comment by Febilian** [comment]
Wow, that was certainly a fast response! Best of luck getting it working, I really love dynamic trees and the fact that it's been getting a lot of mod support lately makes it more fun to use.

**Comment by ferreusveritas** [comment]
The problem was in Dynamic Trees base mod and I've just made a fix for it.  You'll see the fix in the next alpha release whenever that is.
