### ISSUE TITLE
Biomes o' Plenty bamboo doesn't drop bamboo

### ISSUE THREAD

**Issue by Sixdd6** [the-realest-stu/Dynamic-Trees-BOP#16]
Basically what the title says, chopping a fully grown bamboo tree/stalk does not drop any actual bamboo though it does drop around 2 bamboo shoots. Have tried every axe and by hand with same result every time.

Dynamic Trees: 0.7.7e
DT BoP Addon: 1.1d
Biomes o Plenty: 7.0.1.2391
Minecraft: 1.12.2
Forge: 2703

**Comment by whitestarx0312** [comment]
Getting same results.
