### ISSUE TITLE
Bamboo trees not dropping items [1.12.2]

### ISSUE THREAD

**Issue by capt-slowpoke** [the-realest-stu/Dynamic-Trees-BOP#18]
Bamboo trees are not dropping bamboo when harvested with an axe or by hand. All the other Biomes O plenty dynamic trees are working properly

minecraft 1.12.2 
DynamicTrees-1.12.2-0.7.8
BiomesOPlenty-1.12.2-7.0.1.2384-universal

**Comment by SkyHawkB** [comment]
You might be on an old version.

**Comment by SkyHawkB** [comment]
Also, please include the version of DT-BoP when making an issue.

**Comment by capt-slowpoke** [comment]
I was, never mind.
