### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Trees BOP (dynamictreesbop)

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [the-realest-stu/Dynamic-Trees-BOP#4]
I get an error on launch. Crash report here: https://gist.github.com/SlyJacobTheBeast/e3b157e0dd83ca19683a83d49a485cfb

**Comment by ferreusveritas** [comment]
In case the reason this was closed isn't clear.. Dynamic Trees 0.7.5 or later is required.

**Comment by the-realest-stu** [comment]
Yeah, we cleared that up on discord.

**Comment by ferreusveritas** [comment]
I figured, but some people use these closed issues for troubleshooting.  Seemed like a problem that someone else might come across.  Especially since google references these issues during a search.
