### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by Kekko961** [the-realest-stu/Dynamic-Trees-BOP#6]
https://pastebin.com/48jSnMXE

**Comment by SlyJacobTheBeast** [comment]
You need to download alpha version of Dynamic trees (in Twitchapp you can change the setting in the pack in preferred version from release to alpha, otherwise you can download the alpha version straight from the modpage)

**Comment by Lorelando** [comment]
Also duplicates #4 and #5.
A dependency check on startup might clear things up :)

**Comment by the-realest-stu** [comment]
Added a version check to the dependency in the latest alpha, but I'll leave this open for a bit just in case.

**Comment by ferreusveritas** [comment]
Adding a version check has resolved this issue.  This is now only an issue if a user downloads old alpha versions.
